### ISSUE TITLE
Don't combine identical imports

### ISSUE THREAD

**Issue by Wilfred** [Amwam/js-import-sort#16]
Given the (admittedly poor) JS:

```
import {Bouncer} from '../Bouncer';
import Errors from './Errors';
import {Bouncer} from '../Bouncer';
```

js-import-sort produces:

```
import {Bouncer, Bouncer} from '../Bouncer';
import Errors from './Errors';
```

Ideally js-import-sort would remove duplicate values.

**Comment by Amwam** [comment]
Thanks for letting me know about this issue (and the other ones), I'll tackle the rest when I get a bit more time! 
I had a quick hack to resolve this issue for now.
