### ISSUE TITLE
No way of seeing errors

### ISSUE THREAD

**Issue by Wilfred** [Amwam/js-import-sort#18]
When I run js-import-sort, the output ends with:

```
All done. 
Results: 
11 errors
5 unmodified
0 skipped
66 ok
```

Is there any way of seeing these errors? Should I be worried?

**Comment by Amwam** [comment]
Its likely the errors are related to `js-import-sort`, but it should skip the files if it can't do anything

I've added some debugging tools in the latest release, (along with some fixes to the issues you highlights, Thanks for that!)

You can use `--dry --print` to print the results of the transforms to the console, and `--verbose` to get more debugging output.

**Comment by Wilfred** [comment]
Thanks again! :)
