### ISSUE TITLE
js-import-sort removes newline at end of file

### ISSUE THREAD

**Issue by Wilfred** [Amwam/js-import-sort#19]
Given a JS file with a trailing newline:

```
$ cat static/actions.js 
/* eslint no-use-before-define: "off" */
import qs from 'querystring';

export default {
  foo: 1,
};
$
```

js-import-sort removes the trailing newline:

```
$ js-import-sort --path static/actions.js 
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
All done. 
Results: 
0 errors
0 unmodified
0 skipped
1 ok
Time elapsed: 1.734seconds 
$ cat static/actions.js 
/* eslint no-use-before-define: "off" */
import qs from 'querystring';

export default {
  foo: 1,
};$
```

I can work around this by running eslint with `eol-last`, but ideally js-import-sort wouldn't change the newline at the end of the file.

**Comment by Amwam** [comment]
Sorry, I'm going to have to close this, as its not part of this tool. Rather the problem exists as part of either jscodeshfit or recast, in how it processes the results
