### ISSUE TITLE
Feature: support max-len config for better readability

### ISSUE THREAD

**Issue by peritus** [Amwam/js-import-sort#28]
Hey, me again :) Thanks for fixing #21, now this works great on our entire code base without breaking the code. However, ...

Here's an excerpt from one of the file's transformations:

```diff
-import React, {
-  Component,
-  PropTypes
-} from 'react';
-
-import {
-  View,
-  ScrollView,
-  StyleSheet,
-  LayoutAnimation,
-  Animated,
-  TouchableOpacity
-} from 'react-native';
+import React, { Component, PropTypes } from 'react';
+import { Animated, LayoutAnimation, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
```

I agree with the re-formatting of the `react` import being readable one way or another (and yes, honestly I don't care as long as it's consistent).

On the other hand, I don't think the readability of the `react-native` import improved much, quite the opposite.

Would it be possible to support a maximum length (idk, 80, 120, something like that) configuration option for, if the resulting import line would exceed that, the transformer would choose the style that is the original one in the above mentioned example ?

See also: [eslint's max-len rule](http://eslint.org/docs/rules/max-len).

**Comment by Amwam** [comment]
This is something I really want to add in, (its actually keeping whats keeping me from using it in my larger projects).
unfortunately recast (on which this is built on top), doesn't fully support max-len yet. 
I've recently seen [Prettier](https://github.com/jlongster/prettier) which maybe I could integrate with.

For the time being I've just be running `eslint --fix`, its not ideal, but its slightly better.
